
networks:
  book-my-flight:

services:
  backend:
    container_name: bmf-backend
    image: ghcr.io/abhijeetnagar56/bmf-backend:latest
    environment:
      MONGO_URI:
      JWT_SECRET: abc123$%I
      FRONTEND_URL: http://localhost:8080
    ports:
      - "5000:5000"
    networks:
      - book-my-flight
    
  frontend:
    container_name: bmf-frontend
    image: ghcr.io/abhijeetnagar56/bmf-frontend:latest
    ports:
      - "8080:80"
    networks:
      - book-my-flight